## 2.1 판다스

### 2.1.1 판다스로 csv 파일 불러오기

In [67]:
import pandas as pd

In [68]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/sample.csv'

In [69]:
sample = pd.read_csv(file_url)

In [70]:
sample

Var_1  Var_2
0       1      2
1       3      4
2       2      5
3       5      6
4       3      2
5       1      1
6       2      6
7       5      7
8       6      8
9       7      4
10      7      7
11      8      3
12      9      7
13      3      9
14      2      2
15      1      3
16      2      6
17      2      4
18      3      3

### 2.1.2 데이터프레임을 살펴보는 다양한 방법

In [71]:
sample.head()

Var_1  Var_2
0      1      2
1      3      4
2      2      5
3      5      6
4      3      2

In [72]:
sample.head(3)

Var_1  Var_2
0      1      2
1      3      4
2      2      5

In [73]:
sample.tail()

Var_1  Var_2
14      2      2
15      1      3
16      2      6
17      2      4
18      3      3

In [74]:
sample.tail(10)

Var_1  Var_2
9       7      4
10      7      7
11      8      3
12      9      7
13      3      9
14      2      2
15      1      3
16      2      6
17      2      4
18      3      3

In [75]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Var_1   19 non-null     int64
 1   Var_2   19 non-null     int64
dtypes: int64(2)
memory usage: 432.0 bytes


In [76]:
sample.describe()

Var_1      Var_2
count  19.000000  19.000000
mean    3.789474   4.684211
std     2.529360   2.310667
min     1.000000   1.000000
25%     2.000000   3.000000
50%     3.000000   4.000000
75%     5.500000   6.500000
max     9.000000   9.000000

### 2.1.3 데이터프레임 직접 만들기

In [77]:
sample_dic = {'name': ['John','Ann','Kevin'], 'age': [23,22,21]}

In [78]:
pd.DataFrame(sample_dic)

name  age
0   John   23
1    Ann   22
2  Kevin   21

In [79]:
[[1,2],
 [3,4],
 [5,6],
 [7,8]]

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [80]:
pd.DataFrame([[1,2],[3,4],[5,6],[7,8]])

0  1
0  1  2
1  3  4
2  5  6
3  7  8

In [81]:
pd.DataFrame([[1,2],[3,4],[5,6],[7,8]], columns = ['var_1','var_2'], index=['a','b','c','d'])

var_1  var_2
a      1      2
b      3      4
c      5      6
d      7      8

### 2.1.4 데이터프레임 인덱싱

In [82]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/sample_df.csv'

In [83]:
sample_df = pd.read_csv(file_url, index_col=0)

In [84]:
sample_df

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5
d      1      4      5      6      7
e      4      5      7      8      3
f      5      4      8      9      4
g      7      5      2      0      6
h      8      8      1      7      8
i      2      3      5      2      1
j      9      3      7      6      5

In [85]:
sample_df['var_1']

a    2
b    4
c    5
d    1
e    4
f    5
g    7
h    8
i    2
j    9
Name: var_1, dtype: int64

In [86]:
sample_df['var_1', 'var_2']

KeyError: ignored

In [87]:
sample_df[['var_1', 'var_2']]

var_1  var_2
a      2      2
b      4      3
c      5      4
d      1      4
e      4      5
f      5      4
g      7      5
h      8      8
i      2      3
j      9      3

In [88]:
sample_df.loc['a']

var_1    2
var_2    2
var_3    1
var_4    4
var_5    3
Name: a, dtype: int64

In [89]:
sample_df.loc[['a','b','c']]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

In [90]:
sample_df.loc['a':'c']

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

In [91]:
sample_df.iloc[[0,1,2]]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

In [92]:
sample_df.iloc[0:2]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1

In [93]:
sample_df.iloc[0:3]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

In [94]:
sample_df.iloc[0:3, 2:4]

var_3  var_4
a      1      4
b      3      7
c      6      3

In [95]:
sample_df.drop('var_1', axis=1)

var_2  var_3  var_4  var_5
a      2      1      4      3
b      3      3      7      1
c      4      6      3      5
d      4      5      6      7
e      5      7      8      3
f      4      8      9      4
g      5      2      0      6
h      8      1      7      8
i      3      5      2      1
j      3      7      6      5

In [96]:
sample_df.drop(['var_1','var_2'], axis=1)

var_3  var_4  var_5
a      1      4      3
b      3      7      1
c      6      3      5
d      5      6      7
e      7      8      3
f      8      9      4
g      2      0      6
h      1      7      8
i      5      2      1
j      7      6      5

In [97]:
sample_df.drop(['a','b','c'])

var_1  var_2  var_3  var_4  var_5
d      1      4      5      6      7
e      4      5      7      8      3
f      5      4      8      9      4
g      7      5      2      0      6
h      8      8      1      7      8
i      2      3      5      2      1
j      9      3      7      6      5

### 2.1.5 데이터프레임의 인덱스 변경

In [98]:
sample_df.reset_index()

index  var_1  var_2  var_3  var_4  var_5
0     a      2      2      1      4      3
1     b      4      3      3      7      1
2     c      5      4      6      3      5
3     d      1      4      5      6      7
4     e      4      5      7      8      3
5     f      5      4      8      9      4
6     g      7      5      2      0      6
7     h      8      8      1      7      8
8     i      2      3      5      2      1
9     j      9      3      7      6      5

In [99]:
sample_df.reset_index(drop=True)

var_1  var_2  var_3  var_4  var_5
0      2      2      1      4      3
1      4      3      3      7      1
2      5      4      6      3      5
3      1      4      5      6      7
4      4      5      7      8      3
5      5      4      8      9      4
6      7      5      2      0      6
7      8      8      1      7      8
8      2      3      5      2      1
9      9      3      7      6      5

In [100]:
sample_df.set_index('var_1')

var_2  var_3  var_4  var_5
var_1                            
2          2      1      4      3
4          3      3      7      1
5          4      6      3      5
1          4      5      6      7
4          5      7      8      3
5          4      8      9      4
7          5      2      0      6
8          8      1      7      8
2          3      5      2      1
9          3      7      6      5

### 2.1.6 데이터프레임의 변수별 계산

In [101]:
sample_df.sum()

var_1    47
var_2    41
var_3    45
var_4    52
var_5    43
dtype: int64

In [102]:
sample_df.aggregate(['sum','mean'])

var_1  var_2  var_3  var_4  var_5
sum    47.0   41.0   45.0   52.0   43.0
mean    4.7    4.1    4.5    5.2    4.3

### 2.1.7 그룹별 계산

In [103]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/iris.csv'
iris = pd.read_csv(file_url)

In [104]:
iris.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)       class
0                6.1               3.0  ...               1.4  versicolor
1                7.2               3.0  ...               1.6   virginica
2                6.7               3.1  ...               1.4  versicolor
3                6.2               2.9  ...               1.3  versicolor
4                4.6               3.4  ...               0.3      setosa

[5 rows x 5 columns]

In [105]:
iris.groupby('class').mean()

sepal length (cm)  ...  petal width (cm)
class                          ...                  
setosa                  5.006  ...             0.246
versicolor              5.936  ...             1.326
virginica               6.588  ...             2.026

[3 rows x 4 columns]

In [106]:
iris.groupby('class').agg(['count','mean'])

sepal length (cm)         ... petal width (cm)       
                       count   mean  ...            count   mean
class                                ...                        
setosa                    50  5.006  ...               50  0.246
versicolor                50  5.936  ...               50  1.326
virginica                 50  6.588  ...               50  2.026

[3 rows x 8 columns]

### 2.1.8 변수 내 고윳값 확인하기

In [107]:
iris['class'].unique()

array(['versicolor', 'virginica', 'setosa'], dtype=object)

In [108]:
iris['class'].nunique()

3

In [109]:
iris['class'].value_counts()

versicolor    50
virginica     50
setosa        50
Name: class, dtype: int64

### 2.1.8 데이터프레임 합치기

In [110]:
left_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/left.csv'
right_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/right.csv'

left = pd.read_csv(left_url)
right = pd.read_csv(right_url)

In [111]:
left

key  var_1  var_2
0   a      1      1
1   b      3      2
2   c      4      4
3   d      2      3
4   e      1      0

In [112]:
right

key  var_3  var_4
0   b      4      3
1   c      6      5
2   e      3      8
3   f      2      7
4   g      3      4

In [113]:
left.merge(right)

key  var_1  var_2  var_3  var_4
0   b      3      2      4      3
1   c      4      4      6      5
2   e      1      0      3      8

In [114]:
left.merge(right, how = 'outer')

key  var_1  var_2  var_3  var_4
0   a    1.0    1.0    NaN    NaN
1   b    3.0    2.0    4.0    3.0
2   c    4.0    4.0    6.0    5.0
3   d    2.0    3.0    NaN    NaN
4   e    1.0    0.0    3.0    8.0
5   f    NaN    NaN    2.0    7.0
6   g    NaN    NaN    3.0    4.0

In [115]:
left.merge(right, how = 'left')

key  var_1  var_2  var_3  var_4
0   a      1      1    NaN    NaN
1   b      3      2    4.0    3.0
2   c      4      4    6.0    5.0
3   d      2      3    NaN    NaN
4   e      1      0    3.0    8.0

In [121]:
left.join(right)

ValueError: ignored

In [120]:
left.drop('key', axis=1).join(right.drop('key', axis=1))

var_1  var_2  var_3  var_4
0      1      1      4      3
1      3      2      6      5
2      4      4      3      8
3      2      3      2      7
4      1      0      3      4

In [122]:
left = left.set_index('key')
right = right.set_index('key')

In [123]:
left.join(right)

var_1  var_2  var_3  var_4
key                            
a        1      1    NaN    NaN
b        3      2    4.0    3.0
c        4      4    6.0    5.0
d        2      3    NaN    NaN
e        1      0    3.0    8.0

In [124]:
left.join(right, how='inner')

var_1  var_2  var_3  var_4
key                            
b        3      2      4      3
c        4      4      6      5
e        1      0      3      8

In [125]:
pd.concat([left,right])

var_1  var_2  var_3  var_4
key                            
a      1.0    1.0    NaN    NaN
b      3.0    2.0    NaN    NaN
c      4.0    4.0    NaN    NaN
d      2.0    3.0    NaN    NaN
e      1.0    0.0    NaN    NaN
b      NaN    NaN    4.0    3.0
c      NaN    NaN    6.0    5.0
e      NaN    NaN    3.0    8.0
f      NaN    NaN    2.0    7.0
g      NaN    NaN    3.0    4.0

In [128]:
pd.concat([left,right], axis=1)

ValueError: ignored

## 2.2 넘파이

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.array([[[1,2,3],
           [4,5,6],
           [7,8,9]],
          [[1,2,3],
           [4,5,6],
           [7,8,9]],
          [[1,2,3],
           [4,5,6],
           [7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### 2.2.1 배열 생성

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array(sample_df)

array([[2, 2, 1, 4, 3],
       [4, 3, 3, 7, 1],
       [5, 4, 6, 3, 5],
       [1, 4, 5, 6, 7],
       [4, 5, 7, 8, 3],
       [5, 4, 8, 9, 4],
       [7, 5, 2, 0, 6],
       [8, 8, 1, 7, 8],
       [2, 3, 5, 2, 1],
       [9, 3, 7, 6, 5]])

In [ ]:
sample_np = np.array(sample_df)
pd.DataFrame(sample_np)

0  1  2  3  4
0  2  2  1  4  3
1  4  3  3  7  1
2  5  4  6  3  5
3  1  4  5  6  7
4  4  5  7  8  3
5  5  4  8  9  4
6  7  5  2  0  6
7  8  8  1  7  8
8  2  3  5  2  1
9  9  3  7  6  5

In [ ]:
sample_df.columns

Index(['var_1', 'var_2', 'var_3', 'var_4', 'var_5'], dtype='object')

In [ ]:
pd.DataFrame(sample_np, columns = sample_df.columns)

var_1  var_2  var_3  var_4  var_5
0      2      2      1      4      3
1      4      3      3      7      1
2      5      4      6      3      5
3      1      4      5      6      7
4      4      5      7      8      3
5      5      4      8      9      4
6      7      5      2      0      6
7      8      8      1      7      8
8      2      3      5      2      1
9      9      3      7      6      5

### 2.2.2 배열 탐색(인덱싱)

In [ ]:
sample_np

array([[2, 2, 1, 4, 3],
       [4, 3, 3, 7, 1],
       [5, 4, 6, 3, 5],
       [1, 4, 5, 6, 7],
       [4, 5, 7, 8, 3],
       [5, 4, 8, 9, 4],
       [7, 5, 2, 0, 6],
       [8, 8, 1, 7, 8],
       [2, 3, 5, 2, 1],
       [9, 3, 7, 6, 5]])

In [ ]:
sample_np[0]

array([2, 2, 1, 4, 3])

In [ ]:
sample_np[0,2]

1

In [ ]:
sample_np[0:3,2:4]

array([[1, 4],
       [3, 7],
       [6, 3]])

In [ ]:
sample_np[:,2]

array([1, 3, 6, 5, 7, 8, 2, 1, 5, 7])

2.2.3 배열의 연산

In [ ]:
np_a = np.array([[1,3], [0,-2]])

In [ ]:
np_a

array([[ 1,  3],
       [ 0, -2]])

In [ ]:
np_a + 10

array([[11, 13],
       [10,  8]])

In [ ]:
np_a - 5

array([[-4, -2],
       [-5, -7]])

In [ ]:
np_a * 2

array([[ 2,  6],
       [ 0, -4]])

In [ ]:
np_a+10 / 3

array([[4.33333333, 6.33333333],
       [3.33333333, 1.33333333]])

In [ ]:
np_b = np.array([[1,0], [0,1]])
np_b

array([[1, 0],
       [0, 1]])

In [ ]:
np_a + np_b

array([[ 2,  3],
       [ 0, -1]])

In [ ]:
np_a - np_b

array([[ 0,  3],
       [ 0, -3]])

In [ ]:
np_a * np_b

array([[ 1,  0],
       [ 0, -2]])

In [ ]:
np_a @ np_b

array([[ 1,  3],
       [ 0, -2]])

### 2.2.3 일련의 숫자를 만드는 arange() 함수

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

### 2.2.4 시작점과 끝점을 균등한 간격으로 나누는  linspace() 함수


In [ ]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

### 2.2.5 임의의 숫자를 뽑는 random.XXX() 함수

In [ ]:
np.random.randint(11)

10

In [ ]:
np.random.randint(50, 71)

57

In [ ]:
np.random.randint(50, 71, 5)

array([53, 66, 50, 63, 58])

In [ ]:
np.random.choice(['red', 'green','white','black','blue'],size=3)

array(['green', 'green', 'red'], dtype='<U5')

In [ ]:
np.random.choice(['red', 'green','white','black','blue'],size=3, replace=False)

array(['green', 'black', 'white'], dtype='<U5')